# Generated by Django 5.2.15 on 2026-07-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_interviewquestion_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('interview_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
